# This is a workflow that is manually triggered to deploy supported components other than applications

name: Manual Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      invalidations:
        description: |
          If set to 'true', invalidates previous upload.
        default: 'true'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cdn:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variables
    env:
      DRY_RUN: ${{ github.event.inputs.dry_run }}
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'

    # Steps represent a sequence of tasks that will be executed as part of the job    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
      - name: yarn install
        run: >
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >
          .npmrc

          yarn install
      - name: yarn build
        run: yarn build
      - name: upload latest bundle
        uses: CoCreate-app/CoCreate-s3@master
        with:
          aws-key-id: '${{ secrets.AWSACCESSKEYID }}'
          aws-access-key: '${{ secrets.AWSSECERTACCESSKEY }}'
          distributionId: '${{ secrets.DISTRIBUTION_ID }}'
          bucket: testcrudbucket
          source: ./dist
          destination: /latest
          acl: public-read
          invalidations: ${{ github.event.inputs.invalidations }}
      - run: git add .
      - run: git config user.email "frank@cocreate.app"
      - run: git config user.name "frank pagan"
      - run: git commit --allow-empty -m "latest"
      - run: git push origin master
